POST http://localhost:3003/api/blogs 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhYiIsImlkIjoiNjZiMmE3MTg3YzY2YjIwOTMyOWVmYTE5IiwiaWF0IjoxNzIyOTg3MDk1LCJleHAiOjE3MjI5ODcxNTV9.PPeh9HZRXquIYZb4yI5Ktd0m0XRzM0QRF1oS6RNt0d4

{
    "title": "iykyk",
    "author": "abc",
    "url": "http",
    "likes": 4,
    "userId": "66ad4c752b4e08634a5b2b05"
}