DELETE http://localhost:3003/api/blogs/66b131d0fcc747cdfdf4bd61
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY2YWQ0Yzc1MmI0ZTA4NjM0YTViMmIwNSIsImlhdCI6MTcyMjg4ODcxNywiZXhwIjoxNzIyODg4Nzc3fQ.YkxWH0CVv-hP9H6xd5rX4Qs3d9FNy9fLg-OryI6-Wf0